### PR TITLE
demoaudiofiles abstraction and source player for the helpfiles

### PR DESCRIPTION
**Pull request by tremblap**
Here is a programmatic attempt at making a streamlined audiofile loader from our examples - it will also be used in the live source player (fluid.demosound~.pd in progress)

I've included a dummy use in a revised fluid.bufchroma-help.pd

### CODE REVIEW

**Comment by jamesb93** [comment]
I think this is a nice addition to the package.

The interface to me feels like it could benefit from slight guiding for the user.

image

or

image

The same basic principle but more uniform across the selections as well as explicit pointers to the interface that perform the action.

Now I'm. not sure if my install is unorthodox, I set my path to the `release-packaging` and I `ninja install` to there to work. With that setup and when I click "Click here to select a source" I get this:

image

Is that the expected behaviour or maybe not? If it is, what does one do afterwards?

One alternative approach would be to get the path of the package install and instead provide that path to `openpanel` so you can choose a sound by in a native file dialog:

image

Just food for thought, I trust you'll land on a good way.

**Review by jamesb93 — CHANGES_REQUESTED** [review]
The text and buttons could be layed out more uniformly to help guide the user in a very explicit way.

**Comment by jamesb93** [comment]
Ah hold on - it was a meatware issue. I opened the help file in the package above, rather than in the one that `pd`s path was set to and so it didn't hit the media files correctly. I like either approach - the radio buttons are certainly much faster than interfacing with a native dialogue so that's a huge win for that interface.

**Comment by tremblap** [comment]
I have now added a first try at the fluid.demosound~ including 4 types of sources. fluid.chroma~ help is modified temporarily accordingly.

Comments welcome (@jamesb93 I didn't change the order of things yet as I'll gather all comments first)

**Review by tedmoore — APPROVED** [review]

**Comment by jamesb93** [comment]
Was this closed to open: https://github.com/flucoma/flucoma-pd/pull/15 ?

**Comment by tremblap** [comment]
It was closed as approved post improvement and indeed #15 continues the improvement so I prefered not to merge something unfinished...

**Comment by tremblap** [comment]
I almost wanted to ask you how to divide my PRs but with their cross dependencies and everyone being super busy I decided this was a small permissible naughtiness

**Comment by jamesb93** [comment]
It’s not really naughty - I often see closed if the PR somehow exploded or something went wrong (a few examples on learn, core and docs from myself). I just wanted to check that the changes didn’t go missing for some reason.

What I might’ve done in this particular instance is to keep ploughing on the same PR and then request a review again: I think you can do it as many times as you want when you’re the creator (and maybe if youre a reviewer?).

**Comment by tremblap** [comment]
ok next time I'll ask what is the best tactic - now I'm just ploughing on the other one with the new blue styling :)

**Comment by jamesb93** [comment]
> ok next time I'll ask what is the best tactic - now I'm just ploughing on the other one with the new blue styling :)

Either way is fine really. I saw closed and expected it to say merged which is my only surprise. I think if I was working on this particular issue I would have made the changes of this PR the demoaudiofiles and source player abstractions which then would be the only things merged and the experimentation on the chroma help file could either be saved locally or stashed to form a new PR (as you've done). Really the only thing that I wasn't sure of was if the closure was intentional, someone else or something just got lost in translation. Obviously it was intentional after some clarification. 

Of course one other way is to just make a biggish PR that forms you setting up the aesthetic and guts of the future of pd help files which is fine too IMO. Something spiritually similar to the big refactor PR that Owen recently did on docs so for SC.

**Pull request closed without merging**
