### PR TITLE
(buf)chroma help update and overall styling

### PR DESCRIPTION
**Pull request by tremblap**
This is a first attempt at translating the Max new format, including making the help more readable. It also corrects the audiofileloader PR to enable multiple instances

All comments welcome asap.

p

### CODE REVIEW

**Comment by tremblap** [comment]
an experiment in colour (from the website) - yes or no
Screenshot 2022-01-20 at 15 53 04
?

**Comment by jamesb93** [comment]
striking - I actually quite like it :) I think I would have whitespace between the blue and grey parts of the header then you're golden.

**Review by jamesb93 — APPROVED** [review]

**Comment by tremblap** [comment]
Can I add Niamh for aesthetic review?

**Comment by jamesb93** [comment]
Niamh feels these things are true:

1. Niamh also agrees there should be whitespace between blue title and grey subtitle. I would make the gutter between them the sameone that is between the top blue part and the fieldset for activating documentation.
2. The "This class computes a histogram..." is straddling the heading / patching sections of the patch. It should be definitely belonging to one of them. My suggestion would be to move it up a bit and make it aesthetically cogent with the other stuff. How it works in Max is a good guide for how that works. The text should also not use the language of "class" because its not, its an object. 
3. The fieldset for navigating to documentation I am unsure of. Is it more clear to say: Launch the HTML documentation and Launch Learn Reference? I think also you could possibly remove the word launch and just label the button, so: HTML Documentation -> []

**Comment by tremblap** [comment]
ok good, thanks for this. depending on @weefuzzy and @tedmoore review I'll update, finalise, implement in bufchroma and be ready to release.

**Comment by tedmoore** [comment]
I like this very much. You can probably take out the "HTML" in "HTML Reference". Is all reference in Pd HTML?

Just out of curiosity, what is inside of the "More information" button?

**Comment by tremblap** [comment]
> I like this very much.

thanks.

> You can probably take out the "HTML" in "HTML Reference". Is all reference in Pd HTML?

it is not clear and quite a new feature and needs an external browser so I'd leave it there. Very few packages use that feature which is quite new.

> Just out of curiosity, what is inside of the "More information" button?

it is what is in the tab - it has to be a patcher in Pd since there are no tabs. I'll pile them there when there is more than one

**Comment by tremblap** [comment]
let's reopen this

**Review by jamesb93 — APPROVED** [review]

**Comment by tremblap** [comment]
thanks @jamesb93 - let's put a note to review the 2nd panel (which is now different in Max and Pd) in pass2

**Review by tedmoore — APPROVED** [review]

**Pull request merged**
