### PR TITLE
Update QuickStart.md

### PR DESCRIPTION
**Pull request by weefuzzy**
Include a note about adding fluid_libmanipulation to startup libs in QuickStart

### CODE REVIEW

**Comment by weefuzzy** [comment]
See #6

**Comment by tremblap** [comment]
maybe we should also add a link to this: https://learn.flucoma.org/installation/pd

**Comment by weefuzzy** [comment]
Once it's been updated to say "Pd Installation Instructions" (rather than Max), absolutely.

**Comment by tremblap** [comment]
I think @jamesb93 will find this funny

**Comment by tremblap** [comment]
Should I merge and redo the beta4 packages? I think all tests remain to be done, and this is quite a potential problem for new users.

**Comment by weefuzzy** [comment]
Sure

**Pull request merged**
