### PR TITLE
Add feature objects for slicers

### PR DESCRIPTION
**Pull request by weefuzzy**
See https://github.com/flucoma/flucoma-core/pull/114

### CODE REVIEW

**Comment by jamesb93** [comment]
Help file documentation done for this now

**Comment by tremblap** [comment]
I see @jamesb93 is on fire - should I wait for a ping to review?

**Comment by jamesb93** [comment]
go for it now! I struggled to replicate even a fraction of what Max could show with waveform and multislider but the guts are there...

**Comment by tremblap** [comment]
indeed waveform is not done yet (and has the added pleasure of not having all the needed bits in vanilla)

**Comment by weefuzzy** [comment]
It's an audio output yes

**Comment by tremblap** [comment]
ok so that means that this help never worked. I'm fixing them and @tedmoore is showing me how to push on the PR. stay tuned!

**Comment by jamesb93** [comment]
> ok the RT version of the spectral ones generate a lot of 0s between otherwise what I guess are the right onset values. I reckon it is to do with hop size vs (like for all descriptor?) but maybe we could check that fluid.onsetfeatures~ gives the same live stream in Max. At the moment I'm sorting the other helpfile but if @weefuzzy @tedmoore or @jamesb93 can confirm on 'nicol' with the setting in the recently updated pd help generate a lot of zeros. multislider type patch is now in pd so that will help to see what I mean

`onsetfeature` generates a lot of zeroes but spikes in the right places, but `noveltyfeature` with a higher kernelsize should give you something smoother looking.

**Comment by jamesb93** [comment]
image

blue is change filtered, red is the normal one

domain is -1 -1

**Comment by tremblap** [comment]
after updating the bufnovelty version, I can confirm there is a discrepancy of output between the rt and the nrt in pd - if I use a small number of frames on the buf I don't get zeroes between components. @jamesb93 remove the change in your patches (although you would get the interleaved 0s I'm talking about) so @weefuzzy there seem to be a Pd problem here

**Comment by jamesb93** [comment]
> after updating the bufnovelty version, I can confirm there is a discrepancy of output between the rt and the nrt in pd - if I use a small number of frames on the buf I don't get zeroes between components. @jamesb93 remove the change in your patches (although you would get the interleaved 0s I'm talking about) so @weefuzzy there seem to be a Pd problem here

It's occluded by the lack of a third dimension but change is running on one copy (blue) and the unfiltered is red.

**Review by tremblap — APPROVED** [review]
ok this works now as expected. thanks!

**Pull request merged**
