### PR TITLE
remove the data folder being copied in the dev packaging

### PR DESCRIPTION
**Pull request by tremblap**
This removes a copy that is not needed, or at least in the wrong place to be useful.

What could be done is put that copy in /help (and do the same with audiofiles) so it duplicates the delivery package file structure, and both help/media and help/data are gitignored. I actually do that manually at the moment.

I'm happy to change this PR to this plan B or just remove as proposed now since this top level is just not usable for relative path file retrieval (which is used throughout the help file design)

### CODE REVIEW

**Comment by jamesb93** [comment]
I think I understand the problem, the repo folder itself doesn't carry the same structure as the `FluidCorpusManipulation` folder so it doesn't really work to use the top level folder as one's package. Does that mean you (@tremblap) are compiling after every help file change in order to copy `/flucoma-pd/help` to `/flucoma-pd/release-packaging` or are you comitting help files directly to the release-packaging? Seems like a nightmare to work with for you if so!

**Comment by tremblap** [comment]
I work in the repo, and that is why I need (git ignored) copies of media+data in /help - the help isn't found as in a real install but at least I can work on the right file structure.

I think I prefer my 2nd option - adding back the copy that was faulty, putting it in the right place (in help) and copying too the audio at the same time and the same place. If @weefuzzy approves I'll do that and push and merge

**Comment by weefuzzy** [comment]
I have a bunch of handmade symlinks for working with PD during development, which isn't ideal either, however, that's mostly due to the handmade-ness. 

A suggestion: if we bump the min CMake version to 3.14 (current version is 3.22) then we can make symlinks at configure time, meaning that we could have CMake synthesise and maintain a viable working environment for externals, help and resources

**Comment by tremblap** [comment]
this sound erotic. What are the potential pitfalls of cmake bump?

**Comment by tremblap** [comment]
I just noticed that this is more important than I thought, since the mess of development in pd made us forget the concataudiofile in the last 2 beta. @weefuzzy let's spend a few minutes together to brainstorm a good dev folder structure soon-ish.

**Review by weefuzzy — APPROVED** [review]

**Pull request merged**
