### PR TITLE
plotter v0 for review

### PR DESCRIPTION
**Pull request by tremblap**
you need the abstractions in the pd path, and compile against PR58 on core 

i can also do rubberduck if too much pain

### CODE REVIEW

**Comment by jamesb93** [comment]
I have real issues that are beyond a quick fix for compiling on `pd` on m1 so perhaps you should take me off review here, or compile a working version of `pd` for me to use.

**Comment by tremblap** [comment]
You mean Pd the app is not M1 compatible? Otherwise it should work in Roseta2 no?

**Comment by jamesb93** [comment]
It works through rosetta, but compiling throws a bunch of errors. I'll try again now but last time I ended up in a rabbit hole.

**Comment by tremblap** [comment]
deepest of condolences. Compiling woes are the worst. Is Pd M1 native now?

**Comment by jamesb93** [comment]
Looks like whatever soul-selling bargaining Owen did with `cmake` and compiler flags has made the compile process very smooth since I last tried. Things which I'm not sure of:

1. Seems that the plotter's range argument only works on the y axis.
2. In the latest PR for fluid.plotter in `max` and for the `sc` version Ted and I decided range was a little bit weird and unnecessary in bundling x/y ranges. As such we went for `xmin`, `xmax`, `ymin` `ymax`. 
3. The default range is indeed -1, 1 and the other CCE's are 0, 1. I think it should match that of fluid.normalize~ to facilitate rapidly showing some dataset data but thats just me I think.

**Review by weefuzzy — COMMENTED** [review]
Nice work; seems to function nicely as a GUI-ish PD object. I guess in the shiny future, we can look at interaction options. 

I think I'm on board with the idea of a default 0-1 range.

**Comment by tremblap** [comment]
1 and 3 are sorted. still not convinced by non-lists for ranges. will sleep on it

**Comment by jamesb93** [comment]
I'm in two minds about it also. 

In terms of total number of messages there is 1 extra in total for dealing with range for `xmin` etc.. and none of them are just syntactic sugar for each other. On the other hand my mindset for setting the range is that you do it once to set your plotter up then you draw. In that sense one message called range, domain or what have you is more aligned with that use case. It is frustrating to have to deal with `pak f f f f` or `pak f f` everywhere just to change one number though if you want to be more programmatic about it.

**Comment by weefuzzy** [comment]
> In terms of total number of messages there is 1 extra in total for dealing with range for `xmin` etc.. and none of them are just syntactic sugar for each other. 

I've lost the thread of what was there before. You now have 4 messages where there used to be how many? 

> On the other hand my mindset for setting the range is that you do it once to set your plotter up then you draw. 

Not at all sure about that. If the messages are there, *somebody* will use them to zoom and explore, for sure. 

> In that sense one message called range, domain or what have you is more aligned with that use case. It is frustrating to have to deal with `pak f f f f` or `pak f f` everywhere just to change one number though if you want to be more programmatic about it.

Hmm, I'm not totally convinced that `(xmin $1, xmax $2)` would feel much better 😸

**Comment by jamesb93** [comment]
> > In terms of total number of messages there is 1 extra in total for dealing with range for `xmin` etc.. and none of them are just syntactic sugar for each other.
> 
> I've lost the thread of what was there before. You now have 4 messages where there used to be how many?

Three. One for each axis taking two arguments (xrange and orange) and then a range method that would set both axis to the same minima and maxima. So like called xrange and yrange with the same arguments together.
> 
> > On the other hand my mindset for setting the range is that you do it once to set your plotter up then you draw.
> 
> Not at all sure about that. If the messages are there, _somebody_ will use them to zoom and explore, for sure.
> 
> > In that sense one message called range, domain or what have you is more aligned with that use case. It is frustrating to have to deal with `pak f f f f` or `pak f f` everywhere just to change one number though if you want to be more programmatic about it.
> 
> Hmm, I'm not totally convinced that `(xmin $1, xmax $2)` would feel much better 😸

I don't really like it visually but it's got downsides and upsides. Ted said that it's more idiomatic for SC I believe though best to check with him.

**Comment by tremblap** [comment]
> xrange and orange
this made my evening

The rationale when we decide was to match other max gui for such things. Maybe we should minute our interface decision meeting :)

**Comment by jamesb93** [comment]
I remember that conversation. We ripgrepped through the max application contents to see which words were used where.

**Pull request merged**
